[package]
name = "shipmentprocessor"
org = "shashika"
version = "0.1.0"

[build-options]
sticky = true

[[platform.java17.dependency]]
artifactId = "mysql-connector-java"
groupId = "mysql"
version = "8.0.20"
